apiVersion: 1

datasources:
  - name: Taliu PostgreSQL
    uid: taliu-postgres
    type: postgres
    access: proxy
    url: taliu-postgres:5432
    user: taliu
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: taliu
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: false
